name: untitled
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  just_audio: ^0.9.35
  vibration: ^1.7.6
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/sound/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf


    - family: Bekshire
      fonts:
        - asset: assets/fonts/bekshire_swash/BerkshireSwash-Regular.ttf